name: Code Style & Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  run-scanners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        env:
          ImageOS: ubuntu20
        with:
          bundler-cache: true

      - name: Run RuboCop
        run: |
          bin/bundle exec rubocop --config rubocop-must.yml
